version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: boris
      POSTGRES_PASSWORD: ytunymuny
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    
  web:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://boris:ytunymuny@db:5432/mydatabase
      - SECRET_KEY=YSK
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - REFRESH_TOKEN_EXPIRE_DAYS=7
